import {
	COLOR_BLACK,
	COLOR_BROWN_LIGHT,
	COLOR_DARK_BLUE,
  COLOR_LIGHT_BLUE,
  COLOR_ORANGE,
  COLOR_PEACH,
  COLOR_RED,
  COLOR_WHITE,
  COLOR_YELLOW,
} from "./constans";

const NORMAL_BUTTON_SIZE = 40;
const PADDING = 25;

export const BOTTOM_BUTONS = [
  {
    name: "platform",
    topText: "platform",
    bottomText: " 30>",
    color: COLOR_WHITE,
    price: 30,
    hp: 2,
    bottomTextColor: COLOR_LIGHT_BLUE,
    x: PADDING,
    y: 30,
    w: NORMAL_BUTTON_SIZE,
    h: NORMAL_BUTTON_SIZE,
  },
  {
    name: "gun",
    topText: "   gun",
    bottomText: " 20>",
    price: 20,
    hp: 3,
    color: COLOR_LIGHT_BLUE,
    bottomTextColor: COLOR_LIGHT_BLUE,
    x: PADDING * 2 + NORMAL_BUTTON_SIZE,
    y: 30,
    w: NORMAL_BUTTON_SIZE,
    h: NORMAL_BUTTON_SIZE,
  },
  {
    name: "generator",
    topText: "generator",
    bottomText: " 50>",
    price: 50,
    hp: 1,
    color: COLOR_PEACH,
    bottomTextColor: COLOR_LIGHT_BLUE,
    x: PADDING * 3 + NORMAL_BUTTON_SIZE * 2,
    y: 30,
    w: NORMAL_BUTTON_SIZE,
    h: NORMAL_BUTTON_SIZE,
  },
  {
    name: "emp",
    topText: "    EMP",
    bottomText: " 99>",
    price: 99,
    color: COLOR_BLACK,
    bottomTextColor: COLOR_LIGHT_BLUE,
    x: 10 + PADDING * 4 + NORMAL_BUTTON_SIZE * 3,
    y: 20,
    w: NORMAL_BUTTON_SIZE + 10,
    h: NORMAL_BUTTON_SIZE + 10,
  },
  {
    name: "rocket",
    topText: "  rocket",
    bottomText: " 40>",
    price: 40,
    hp: 5,
    color: COLOR_ORANGE,
    bottomTextColor: COLOR_LIGHT_BLUE,
    x: PADDING * 6 + NORMAL_BUTTON_SIZE * 4,
    y: 30,
    w: NORMAL_BUTTON_SIZE,
    h: NORMAL_BUTTON_SIZE,
  },
  {
    name: "shield",
    topText: "  shield",
    bottomText: " 35>",
    price: 35,
    hp: 2,
    color: COLOR_DARK_BLUE,
    bottomTextColor: COLOR_LIGHT_BLUE,
    x: PADDING * 7 + NORMAL_BUTTON_SIZE * 5,
    y: 30,
    w: NORMAL_BUTTON_SIZE,
    h: NORMAL_BUTTON_SIZE,
  },
  {
    name: "sgun",
    topText: "score gun",
    bottomText: " 100",
    price: 100,
    hp: 6,
    color: COLOR_YELLOW,
    bottomTextColor: COLOR_YELLOW,
    x: PADDING * 8 + NORMAL_BUTTON_SIZE * 6,
    y: 30,
    w: NORMAL_BUTTON_SIZE,
    h: NORMAL_BUTTON_SIZE,
  },
];
